name = "fuel-price-ingest"
main = "src/index.ts"
compatibility_date = "2026-09-18"

[[d1_databases]]
binding = "DB"
database_name = "fuel-price-db"
database_id = "787ba73c-d186-463b-af39-d7053427ff8a"
migrations_dir = "../../db/migrations"
